### PR TITLE
Database Datastore commits

### PR DESCRIPTION
**Pull request by tobaolo**

### CODE REVIEW

**Comment by qi-google** [comment]
Seems like you have checked in unrelated files, can you resolve the conflicts first?

**Comment by qi-google** [comment]
I think the change to the `comment.java` should go with this PR since this PR touches the datastore interaction and index addition. We can focus on this PR first and get it merged.

**Comment by tobaolo** [comment]
The comment.java file is in this PR. Have updated and ready to merge (i hope haha) @qi-google

**Comment by qi-google** [comment]
I think you forgot to `git add xx/Comment.java` and commit.

**Pull request merged**
